CMD arg for specify where Zork++ start it's job from any place (#98)
* version: 0.8.7

diff --git a/.github/workflows/code-quality.yml b/.github/workflows/code-quality.yml
--- a/.github/workflows/code-quality.yml
+++ b/.github/workflows/code-quality.yml
@@ -59,11 +59,36 @@ jobs:
 
       - name: Get the latest Clang version available
         run: |
-          clang++ -v
+          set -e  # Exit on error
+          echo "-----> clang installation directory"
+          which clang++
+          echo "-----> clang binary version"
+          clang++ --version
+          
+          echo "-----> installing Clang 15"
+          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
           sudo apt update
-          sudo apt install clang-15 --install-suggests
+          
+          echo "-----> Adding the LLVM repository for the version 15"
+          sudo apt-add-repository "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-15 main"
+          
+          echo "-----> Installing Clang 15"
+          sudo apt install --install-suggests clang-15
+          
+          echo "-----> Installing libc++"
+          sudo apt install libc++-15-dev libc++abi-15-dev libunwind-15 libunwind-15-dev libc6 libzstd1
+          
+          echo "-----> Removing the symbolic link to the default version"
+          sudo rm -f /usr/bin/clang++
+          echo "-----> Creating the symbolic link to the new Clang 15 version"
+          sudo ln -s /usr/bin/clang++-15 /usr/bin/clang++
+          
+          echo "-----> Clang-15 was installed on:"
+          which clang-15
+          echo "-----> Clang++ was installed on:"
+          which clang++-15
 
       - name: Running the tests for the project
         run: |
           cd zork++
-          cargo test --all
+          RUST_LOG=trace cargo test 2>&1 --all --color=always --no-fail-fast -- --nocapture --show-output --test-threads=1
